# Problem 1

**A.** Create a one-dimensional NumPy array using np.arange method.

*Sample Output:*

    array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16])


In [431]:
import numpy as np

#Usage of Lambda Function - sticking info into long term memory!
createNDarray = lambda n: np.arange(n)

arr = createNDarray(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

**B.** Reshape the array to make it two-dimensional array of 4X4 size:

*Sample Output:*

    array([ [ 1, 2, 3, 4],

          [ 5, 6, 7, 8],

          [ 9, 10, 11,12],

          [13, 14, 15,16]])

In [432]:
reshapedArray = arr.reshape(4,4)
reshapedArray

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**C.** Split the array into four equal-sized(2X2) sub-arrays.

*Sample Output:*

    array([ [ 1, 2],
            [ 5, 6]])

    array([ [ 3, 4],
            [ 7, 8]])

    array([ [ 9, 10],
            [13, 14]])

    array([ [11, 12],
            [15, 16]])

In [433]:
splitedArray = reshapedArray[0:2, 0:2], reshapedArray[0:2, 2:4], reshapedArray[2:4, 0:2], reshapedArray[2:4, 2:4]
splitedArray

(array([[0, 1],
        [4, 5]]),
 array([[2, 3],
        [6, 7]]),
 array([[ 8,  9],
        [12, 13]]),
 array([[10, 11],
        [14, 15]]))

# Problem 2
Generate a random password that meets the following conditions:

**A.** Password length must be 4 characters long.


In [434]:
import random
import string

#Generate a random password of length 4
def generatePassword():
    passwordLength = 4
    password = ""
    
    #Generate each character of the password
    for i in range(passwordLength):
        isNum = random.getrandbits(1)
        
        #Append a number to password if isNum bit is 1
        if(isNum):
            password = password + (str)(random.choice(range(10)))
        
        #Append an alphabet character to password if IsNum bit is 0
        else:
            #Citation: found help on generating a random ASCII letter from "Mark Rushakoff on Stack Overflow"
            #Link: https://stackoverflow.com/questions/2823316/generate-a-random-letter-in-python
            password = password + random.choice(string.ascii_letters)
        
    return password 

generatePassword()

'70I5'

**B.** It must contain at least 1 upper case letter, 1 digit.

*Sample Output:*

    Password: 4Bvr

In [435]:
def generatePasswordWithConditions():
    """
    Generate a password with the generatePassword function and ensures that the result contains at least:
        - 1 upper case letter.
        - 1 digit.
    before returning the password. Otherwise, generate another password and repeat steps until conditions met.
    """
    while True:
        password = generatePassword()
        hasUpper = False
        hasDigit = False
        
        #Conditions Checking
        for i in range(len(password)):
            #Check if char is uppercase
            #Citation: found how to check if character is uppercase from w3schools
            #Link: https://www.w3schools.com/python/ref_string_isupper.asp
            if(password[i].isupper()):
                hasUpper = True
                
            #Check if char is a digit
            #Citation: found how to check if character is numeric from w3schools
            #Link: https://www.w3schools.com/python/ref_string_isnumeric.asp
            if(password[i].isnumeric()):
                hasDigit = True
        
        if(hasDigit & hasUpper):
            return password
        
        else:
            generatePasswordWithConditions()
    
generatePasswordWithConditions()

'E0T3'

# Problem 3

**A.** Generate a random 2-D integer array of size N X M where N and M are the numbers of rows and columns. Print the mean from axis 0 and sum from axis 1.

*Sample Output:*

    array([ [ 3, 8],
            [ 7, 5]
         ])
    Mean (axis 0) = 5.0, 6.5
    Sum (axis 1) = 11, 12


In [436]:
#Output array

#Generate an ndArray of size N x M with random integers from 0 to 100
genRandomNDArray = lambda n,m: np.random.randint(0, 100, (n, m))

array = genRandomNDArray(2, 2)
array


array([[66, 29],
       [16, 96]])

In [437]:
#Output mean and sum of respective axises

#Convert ndArray to printable string format and return string
def ndArrayToString(array):
    result = ""
    
    for items in array:
        #Initialize result string with first element if string is empty
        if len(result) == 0:
            result = result + (str)(items)
            
        else:
            result = result + ", " + (str)(items)
        
    
    return result
    
#Output mean of axis 0
print("Mean (axis 0) = " + ndArrayToString(array.mean(0)))

#Output 
print("Sum (axis 1) = " + ndArrayToString(array.sum(1)))

Mean (axis 0) = 41.0, 62.5
Sum (axis 1) = 95, 112


# Problem 4

Read the data from the files (wordFeature.txt, wordInput.txt) and create two NumPy arrays from the data. Print the words where the average of features is greater than 500 (Using np.where method). Also, write the output into a file (wordoutput.txt).

In [438]:
inputList = open("wordInput.txt").read().split("\n")
featureList = open("wordFeature.txt").read()

print(inputList)
print(featureList)

['Word', 'AI', 'CMU', 'Data', 'ML', 'CNN', 'Classifier']
Count, Importance
300.0, 253.25
200.0, 232.56
342.0, 345.66
232.0, 211.99
234.0, 789.88
212.0, 345.88


In [439]:
import re

inputArray = np.array(inputList)[1:]

#Citation: found how to split with two different options using regular expression from Stack Overflow
#Link: https://stackoverflow.com/questions/4998629/split-string-with-multiple-delimiters-in-python
featureArray = np.array(re.split(", |\n", featureList)).reshape(7,2)[1:].astype(np.float32)
averageFeatureArray = (featureArray[:, 0] + featureArray[:, 1]) / 2

averageFeatureArray

array([276.625  , 216.28   , 343.83002, 221.995  , 511.94   , 278.94   ],
      dtype=float32)

In [440]:
inputArray

array(['AI', 'CMU', 'Data', 'ML', 'CNN', 'Classifier'], dtype='<U10')

In [441]:
#Grab words where its features' average is above 500 and store it in resultArray
resultArray = np.where(averageFeatureArray > 500, inputArray, None)
resultArray

array([None, None, None, None, 'CNN', None], dtype=object)

In [442]:
resultString = "Words where the average of features is greater than 500:"

#Check if items in array is null; disregard if word is None and add to file if word is valid
for words in resultArray:
    if words != None:
        print(words)
        resultString = resultString + "\n" + words

output = open("wordoutput.txt", "w")
output.write(resultString)

CNN


60